name: lotto
description: 로또번호생성기
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+9

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  quiver: ^3.2.1
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.18.0
  settings_ui: ^2.0.2
  mobile_scanner: ^6.0.2
  dio: ^5.7.0
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.3.0
  google_mobile_ads: ^5.2.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Bold.otf
        - asset: assets/fonts/SUIT-ExtraBold.otf
        - asset: assets/fonts/SUIT-ExtraLight.otf
        - asset: assets/fonts/SUIT-Heavy.otf
        - asset: assets/fonts/SUIT-Light.otf
        - asset: assets/fonts/SUIT-Medium.Otf
        - asset: assets/fonts/SUIT-Regular.otf
        - asset: assets/fonts/SUIT-SemiBold.otf
        - asset: assets/fonts/SUIT-Thin.otf

  assets:
    - .env
    - assets/splash/

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/logo.png
  branding: assets/splash/branding.png
  image_dark: assets/splash/logo.png
  branding_dark: assets/splash/branding.png
  android_12:
    color: "#ffffff"
    image: assets/splash/logo12.png
    branding: assets/splash/branding12.png
    color_dark: "#ffffff"
    image_dark: assets/splash/logo12.png
    branding_dark: assets/splash/branding12.png
